name: 'CosmosMapper'
description: 'Generate schema documentation for Azure Cosmos DB with ERD diagrams'
author: 'afrugalpenguin'

branding:
  icon: 'database'
  color: 'blue'

inputs:
  cosmos-endpoint:
    description: 'Azure Cosmos DB endpoint URL'
    required: true
  cosmos-key:
    description: 'Cosmos DB read-only key (omit for managed identity/Azure AD)'
    required: false
    default: ''
  databases:
    description: 'Comma-separated database names (empty = all databases)'
    required: false
    default: ''
  output-dir:
    description: 'Output directory for generated documentation'
    required: false
    default: './cosmos-docs'
  formats:
    description: 'Output formats: markdown, html, jsonschema (comma-separated)'
    required: false
    default: 'markdown,html'
  sample-size:
    description: 'Number of documents to sample per container'
    required: false
    default: '100'
  diff:
    description: 'Compare against previous snapshot'
    required: false
    default: 'false'
  snapshot:
    description: 'Save snapshot with this name (empty = no snapshot)'
    required: false
    default: ''
  fail-on-breaking:
    description: 'Exit with code 1 if breaking schema changes detected'
    required: false
    default: 'false'
  validate:
    description: 'Enable relationship data validation (slower)'
    required: false
    default: 'false'

outputs:
  html-report:
    description: 'Path to the generated HTML report'
    value: ${{ steps.run.outputs.html-report }}
  has-breaking-changes:
    description: 'Whether breaking changes were detected (true/false)'
    value: ${{ steps.run.outputs.has-breaking-changes }}
  exit-code:
    description: 'Exit code from CosmosMapper'
    value: ${{ steps.run.outputs.exit-code }}

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: ${{ github.action_path }}/package-lock.json

    - name: Install dependencies
      shell: bash
      working-directory: ${{ github.action_path }}
      run: npm ci --prefer-offline

    - name: Run CosmosMapper
      id: run
      shell: bash
      working-directory: ${{ github.action_path }}
      env:
        COSMOS_ENDPOINT: ${{ inputs.cosmos-endpoint }}
        COSMOS_KEY: ${{ inputs.cosmos-key }}
      run: |
        # Build command arguments
        ARGS="--output ${{ inputs.output-dir }} --format ${{ inputs.formats }} --sample-size ${{ inputs.sample-size }} --quiet"

        if [ -n "${{ inputs.databases }}" ]; then
          ARGS="$ARGS --databases ${{ inputs.databases }}"
        fi

        if [ "${{ inputs.diff }}" = "true" ]; then
          ARGS="$ARGS --diff"
        fi

        if [ -n "${{ inputs.snapshot }}" ]; then
          ARGS="$ARGS --snapshot ${{ inputs.snapshot }}"
        fi

        if [ "${{ inputs.fail-on-breaking }}" = "true" ]; then
          ARGS="$ARGS --fail-on-breaking"
        fi

        if [ "${{ inputs.validate }}" = "true" ]; then
          ARGS="$ARGS --validate"
        fi

        echo "Running: node src/index.js $ARGS"

        # Run and capture exit code
        set +e
        node src/index.js $ARGS
        EXIT_CODE=$?
        set -e

        # Set outputs
        echo "exit-code=$EXIT_CODE" >> $GITHUB_OUTPUT
        echo "html-report=${{ inputs.output-dir }}/schema-report.html" >> $GITHUB_OUTPUT

        if [ $EXIT_CODE -eq 1 ] && [ "${{ inputs.fail-on-breaking }}" = "true" ]; then
          echo "has-breaking-changes=true" >> $GITHUB_OUTPUT
        else
          echo "has-breaking-changes=false" >> $GITHUB_OUTPUT
        fi

        # Exit with original code
        exit $EXIT_CODE
